-- zuzu v2 — seed: regions, the city → region map, sources.
-- Regions and cities are copied from v1 (index.html CITY_REGION). D5 asked for a fixed
-- list of ~8; v1 has these 7 (online and abroad are venue kinds now, not regions).
-- Edit freely: the site label can change without touching data.

insert into regions (code, label_he, sort) values
  ('tel_aviv',    'תל אביב',           1),
  ('sharon',      'שרון',              2),
  ('pardes_hana', 'פרדס חנה והסביבה',  3),
  ('center',      'מרכז',              4),
  ('jerusalem',   'ירושלים',           5),
  ('north',       'צפון',              6),
  ('south',       'דרום',              7)
on conflict (code) do update set label_he = excluded.label_he, sort = excluded.sort;

insert into cities (name, region_code) values
  ('תל אביב', 'tel_aviv'),
  ('תל אביב-יפו', 'tel_aviv'),
  ('יפו', 'tel_aviv'),
  ('רמת גן', 'tel_aviv'),
  ('גבעתיים', 'tel_aviv'),
  ('בת ים', 'tel_aviv'),
  ('חולון', 'tel_aviv'),
  ('בני ברק', 'tel_aviv'),
  ('הרצליה', 'sharon'),
  ('רעננה', 'sharon'),
  ('כפר סבא', 'sharon'),
  ('הוד השרון', 'sharon'),
  ('רמת השרון', 'sharon'),
  ('נתניה', 'sharon'),
  ('אבן יהודה', 'sharon'),
  ('אודים', 'sharon'),
  ('עדנים', 'sharon'),
  ('מושב חרות', 'sharon'),
  ('השרון', 'sharon'),
  ('צור יגאל', 'sharon'),
  ('כפר יונה', 'sharon'),
  ('תל מונד', 'sharon'),
  ('קדימה', 'sharon'),
  ('צורן', 'sharon'),
  ('קלנסווה', 'sharon'),
  ('רחובות', 'center'),
  ('ראשון לציון', 'center'),
  ('נס ציונה', 'center'),
  ('רמלה', 'center'),
  ('לוד', 'center'),
  ('פתח תקווה', 'center'),
  ('ראש העין', 'center'),
  ('יבנה', 'center'),
  ('גדרה', 'center'),
  ('גן יבנה', 'center'),
  ('באר יעקב', 'center'),
  ('יהוד', 'center'),
  ('אור יהודה', 'center'),
  ('אריאל', 'center'),
  ('טל שחר', 'center'),
  ('רעות', 'center'),
  ('מכבים', 'center'),
  ('שוהם', 'center'),
  ('ירושלים', 'jerusalem'),
  ('מבשרת ציון', 'jerusalem'),
  ('בית שמש', 'jerusalem'),
  ('מעלה אדומים', 'jerusalem'),
  ('נטף', 'jerusalem'),
  ('מודיעין', 'jerusalem'),
  ('עין כרם', 'jerusalem'),
  ('אבן ספיר', 'jerusalem'),
  ('באר שבע', 'south'),
  ('אשדוד', 'south'),
  ('אשקלון', 'south'),
  ('מצפה רמון', 'south'),
  ('ערד', 'south'),
  ('דימונה', 'south'),
  ('אילת', 'south'),
  ('שדרות', 'south'),
  ('נתיבות', 'south'),
  ('אופקים', 'south'),
  ('מיתר', 'south'),
  ('להבים', 'south'),
  ('עומר', 'south'),
  ('קריית גת', 'south'),
  ('קרית גת', 'south'),
  ('חיפה', 'north'),
  ('כרמיאל', 'north'),
  ('נהריה', 'north'),
  ('עכו', 'north'),
  ('צפת', 'north'),
  ('טבריה', 'north'),
  ('קריית שמונה', 'north'),
  ('עפולה', 'north'),
  ('נצרת', 'north'),
  ('מגדל העמק', 'north'),
  ('יקנעם', 'north'),
  ('כפר בלום', 'north'),
  ('עמק יזרעאל', 'north'),
  ('גניגר', 'north'),
  ('בית לחם הגלילית', 'north'),
  ('רמת ישי', 'north'),
  ('כפר ורדים', 'north'),
  ('מעלות', 'north'),
  ('שלומי', 'north'),
  ('ראש פינה', 'north'),
  ('בית שאן', 'north'),
  ('קריית ביאליק', 'north'),
  ('קריית מוצקין', 'north'),
  ('קריית ים', 'north'),
  ('קריית אתא', 'north'),
  ('קריות', 'north'),
  ('מגידו', 'north'),
  ('פרדס חנה', 'pardes_hana'),
  ('פרדס חנה-כרכור', 'pardes_hana'),
  ('כרכור', 'pardes_hana'),
  ('עין שמר', 'pardes_hana'),
  ('חדרה', 'pardes_hana'),
  ('זכרון יעקב', 'pardes_hana'),
  ('בנימינה', 'pardes_hana'),
  ('גבעת עדה', 'pardes_hana'),
  ('קיסריה', 'pardes_hana'),
  ('אור עקיבא', 'pardes_hana'),
  ('מעגן מיכאל', 'pardes_hana')
on conflict (name) do update set region_code = excluded.region_code;

-- Spellings seen in the v1 sheet that the map above misses.
insert into cities (name, region_code) values
  ('תל אביב יפו', 'tel_aviv'),
  ('גן שמואל', null),             -- no region in v1 either: the bot asks
  ('מנשה', 'sharon'),
  ('עין-שמר', 'pardes_hana')
on conflict (name) do nothing;

-- E2: the v1 policy, now per source. New sources default to review-only.
insert into sources (id, name, kind, auto_publish) values
  ('manual',                 'Pasted into the bot',             'manual',     false),
  ('inbox',                  'zuzu-inbox posters',              'inbox',      false),
  ('newsletter',             'zuzu-inbox newsletters',          'newsletter', false),
  ('bodyways',               'bodyways.org',                    'scrape',     false),
  ('ecstatic',               'ecstaticdance.co.il',             'scrape',     true),
  ('tribe:gagapeople',       'gagapeople.com (Events Calendar)','tribe',      true),
  ('tribe:choreographers',   'choreographers.org.il',           'tribe',      true),
  ('v1',                     'Import from the v1 sheet',        'manual',     false)
on conflict (id) do nothing;
